<?php

namespace App\Http\Controllers;

use App\Exceptions\Handler;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\RedirectResponse;
use Illuminate\Validation\ValidationException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use App\Models\User;
use App\Models\DocObl;
use App\Models\DocOblHistori;
use Carbon\Carbon;

class SolutionController extends Controller
{
    public function kembaliWitel(Request $request){
      // dd($request->all());
      if( $request->kw_obl_id ){
        try{
          $doc_to_histori = DB::connection('pgsql')->table('form_obl')->select('*')->where('id',$request->kw_obl_id)->first();

          DB::connection('pgsql')->table('form_obl_histori')->insert([
            'obl_id' => $doc_to_histori->id,
            'submit' => $doc_to_histori->submit,
            'revisi_witel' => $doc_to_histori->revisi_witel,
            'revisi_witel_count' => $doc_to_histori->revisi_witel_count,
            'is_draf' => $doc_to_histori->is_draf,
            'updated_at' => $doc_to_histori->updated_at,
            'updated_by' => $doc_to_histori->updated_by,
            'f1_nama_plggn' => $doc_to_histori->f1_nama_plggn,
            'f1_alamat_plggn' => $doc_to_histori->f1_alamat_plggn,
            'f1_witel' => $doc_to_histori->f1_witel,
            'f1_judul_projek' => $doc_to_histori->f1_judul_projek,
            'f1_segmen' => $doc_to_histori->f1_segmen,
            'f1_proses' => $doc_to_histori->f1_proses,
            'f1_folder' => $doc_to_histori->f1_folder,
            'f1_nilai_kb' => $doc_to_histori->f1_nilai_kb,
            'f1_no_kfs_spk' => $doc_to_histori->f1_no_kfs_spk,
            'f1_quote_kontrak' => $doc_to_histori->f1_quote_kontrak,
            'f1_nomor_akun' => $doc_to_histori->f1_nomor_akun,
            'f1_jenis_kontrak' => $doc_to_histori->f1_jenis_kontrak,
            'f1_skema_bayar' => $doc_to_histori->f1_skema_bayar,
            'f1_status_order' => $doc_to_histori->f1_status_order,
            'f1_status_sm' => $doc_to_histori->f1_status_sm,
            'f1_tgl_keterangan' => $doc_to_histori->f1_tgl_keterangan,
            'f1_keterangan' => $doc_to_histori->f1_keterangan,
            'f1_mitra_id' => $doc_to_histori->f1_mitra_id,
            'f1_pic_mitra' => $doc_to_histori->f1_pic_mitra,
            'f1_jenis_spk' => $doc_to_histori->f1_jenis_spk,
            'f1_masa_layanan_tahun' => $doc_to_histori->f1_masa_layanan_tahun,
            'f1_masa_layanan_bulan' => $doc_to_histori->f1_masa_layanan_bulan,
            'f1_masa_layanan_hari' => $doc_to_histori->f1_masa_layanan_hari,
            'f1_pic_plggn' => $doc_to_histori->f1_pic_plggn,
            'f2_nilai_kontrak' => $doc_to_histori->f2_nilai_kontrak,
            'f2_tgl_p1' => $doc_to_histori->f2_tgl_p1,
            'p2_tgl_p2' => $doc_to_histori->p2_tgl_p2,
            'p2_tgl_justifikasi' => $doc_to_histori->p2_tgl_justifikasi,
            'p2_dievaluasi_oleh' => $doc_to_histori->p2_dievaluasi_oleh,
            'p2_disetujui_oleh' => $doc_to_histori->p2_disetujui_oleh,
            'p2_pilihan_catatan' => $doc_to_histori->p2_pilihan_catatan,
            'p2_catatan' => $doc_to_histori->p2_catatan,
            'p3_tgl_p3' => $doc_to_histori->p3_tgl_p3,
            'p3_takah_p3' => $doc_to_histori->p3_takah_p3,
            'p3_pejabat_mitra_nama' => $doc_to_histori->p3_pejabat_mitra_nama,
            'p3_pejabat_mitra_alamat' => $doc_to_histori->p3_pejabat_mitra_alamat,
            'p3_pejabat_mitra_telepon' => $doc_to_histori->p3_pejabat_mitra_telepon,
            'p3_status_rapat_pengadaan' => $doc_to_histori->p3_status_rapat_pengadaan,
            'p3_tgl_rapat_pengadaan' => $doc_to_histori->p3_tgl_rapat_pengadaan,
            'p3_tmpt_rapat_pengadaan' => $doc_to_histori->p3_tmpt_rapat_pengadaan,
            'p3_tgl_terima_sp' => $doc_to_histori->p3_tgl_terima_sp,
            'p3_alamat_terima_sp' => $doc_to_histori->p3_alamat_terima_sp,
            'p3_manager_obl' => $doc_to_histori->p3_manager_obl,
            'p4_tgl_p4' => $doc_to_histori->p4_tgl_p4,
            'p4_waktu_layanan' => $doc_to_histori->p4_waktu_layanan,
            'p4_skema_bisnis' => $doc_to_histori->p4_skema_bisnis,
            'p4_mekanisme_pembayaran' => $doc_to_histori->p4_mekanisme_pembayaran,
            'p4_slg' => $doc_to_histori->p4_slg,
            'p4_fasilitator' => $doc_to_histori->p4_fasilitator,
            'p4_pengesahan' => $doc_to_histori->p4_pengesahan,
            'p5_tgl_p5' => $doc_to_histori->p5_tgl_p5,
            'p5_harga_penawaran' => $doc_to_histori->p5_harga_penawaran,
            'p5_ttd_evaluator' => $doc_to_histori->p5_ttd_evaluator,
            'p6_tgl_p6' => $doc_to_histori->p6_tgl_p6,
            'p6_ttd_bast_telkom' => $doc_to_histori->p6_ttd_bast_telkom,
            'p6_ttd_bast_mitra' => $doc_to_histori->p6_ttd_bast_mitra,
            'p6_harga_negosiasi' => $doc_to_histori->p6_harga_negosiasi,
            'p6_nama_peserta_mitra' => $doc_to_histori->p6_nama_peserta_mitra,
            'p6_jabatan_peserta_mitra' => $doc_to_histori->p6_jabatan_peserta_mitra,
            'p6_peserta_rapat_telkom' => $doc_to_histori->p6_peserta_rapat_telkom,
            'p6_pengesahan' => $doc_to_histori->p6_pengesahan,
            'p7_tgl_p7' => $doc_to_histori->p7_tgl_p7,
            'p7_takah_p7' => $doc_to_histori->p7_takah_p7,
            'p7_lampiran_berkas' => $doc_to_histori->p7_lampiran_berkas,
            'p7_harga_pekerjaan' => $doc_to_histori->p7_harga_pekerjaan,
            'p7_skema_bayar' => $doc_to_histori->p7_skema_bayar,
            'p7_pemeriksa' => $doc_to_histori->p7_pemeriksa,
            'p7_tembusan' => $doc_to_histori->p7_tembusan,
            'sp_tgl_sp' => $doc_to_histori->sp_tgl_sp,
            'sp_takah_sp' => $doc_to_histori->sp_takah_sp,
            'sp_nomor_kb' => $doc_to_histori->sp_nomor_kb,
            'p8_tgl_p8' => $doc_to_histori->p8_tgl_p8,
            'p8_takah_p8' => $doc_to_histori->p8_takah_p8,
            'wo_tgl_wo' => $doc_to_histori->wo_tgl_wo,
            'wo_takah_wo' => $doc_to_histori->wo_takah_wo,
            'wo_tgl_fo' => $doc_to_histori->wo_tgl_fo,
            'wo_nomor_kb' => $doc_to_histori->wo_nomor_kb,
            'wo_jenis_layanan' => $doc_to_histori->wo_jenis_layanan,
            'wo_jumlah_layanan' => $doc_to_histori->wo_jumlah_layanan,
            'wo_harga_ke_plggn' => $doc_to_histori->wo_harga_ke_plggn,
            'wo_onetime_charge_plggn' => $doc_to_histori->wo_onetime_charge_plggn,
            'wo_monthly_plggn' => $doc_to_histori->wo_monthly_plggn,
            'wo_onetime_charge_telkom' => $doc_to_histori->wo_onetime_charge_telkom,
            'wo_persen_telkom' => $doc_to_histori->wo_persen_telkom,
            'wo_monthly_telkom' => $doc_to_histori->wo_monthly_telkom,
            'wo_onetime_charge_mitra' => $doc_to_histori->wo_onetime_charge_mitra,
            'wo_persen_mitra' => $doc_to_histori->wo_persen_mitra,
            'wo_monthly_mitra' => $doc_to_histori->wo_monthly_mitra,
            'kl_tgl_kl' => $doc_to_histori->kl_tgl_kl,
            'kl_takah_kl' => $doc_to_histori->kl_takah_kl,
            'kl_nomor_kb' => $doc_to_histori->kl_nomor_kb,
            'kl_no_kl_mitra' => $doc_to_histori->kl_no_kl_mitra,
            'kl_tempat_ttd_kl' => $doc_to_histori->kl_tempat_ttd_kl,
            'kl_notaris' => $doc_to_histori->kl_notaris,
            'kl_akta_notaris' => $doc_to_histori->kl_akta_notaris,
            'kl_tgl_akta_notaris' => $doc_to_histori->kl_tgl_akta_notaris,
            'kl_nama_pejabat_telkom' => $doc_to_histori->kl_nama_pejabat_telkom,
            'kl_jabatan_pejabat_telkom' => $doc_to_histori->kl_jabatan_pejabat_telkom,
            'kl_npwp_mitra' => $doc_to_histori->kl_npwp_mitra,
            'kl_no_anggaran_mitra' => $doc_to_histori->kl_no_anggaran_mitra,
            'kl_tgl_anggaran_mitra' => $doc_to_histori->kl_tgl_anggaran_mitra,
            'kl_nama_pejabat_mitra' => $doc_to_histori->kl_nama_pejabat_mitra,
            'kl_jabatan_pejabat_mitra' => $doc_to_histori->kl_jabatan_pejabat_mitra,
            'kl_no_skm' => $doc_to_histori->kl_no_skm,
            'kl_tgl_skm' => $doc_to_histori->kl_tgl_skm,
            'kl_perihal_skm' => $doc_to_histori->kl_perihal_skm,
            'kl_tgl_akhir_kl' => $doc_to_histori->kl_tgl_akhir_kl,
            'kl_bayar_dp' => $doc_to_histori->kl_bayar_dp,
            'kl_nama_bank_mitra' => $doc_to_histori->kl_nama_bank_mitra,
            'kl_cabang_bank_mitra' => $doc_to_histori->kl_cabang_bank_mitra,
            'kl_rek_bank_mitra' => $doc_to_histori->kl_rek_bank_mitra,
            'kl_an_bank_mitra' => $doc_to_histori->kl_an_bank_mitra,
            'file_p2' => $doc_to_histori->file_p2,
            'file_p3' => $doc_to_histori->file_p3,
            'file_p4' => $doc_to_histori->file_p4,
            'file_p5' => $doc_to_histori->file_p5,
            'file_p6' => $doc_to_histori->file_p6,
            'file_p7' => $doc_to_histori->file_p7,
            'file_p8' => $doc_to_histori->file_p8,
            'file_sp' => $doc_to_histori->file_sp,
            'file_wo' => $doc_to_histori->file_wo,
            'file_kl' => $doc_to_histori->file_kl,
            'p0_nomor_p0' => $doc_to_histori->p0_nomor_p0,
            'p0_nik_am' => $doc_to_histori->p0_nik_am,
            'p0_nik_manager' => $doc_to_histori->p0_nik_manager,
            'p0_tgl_submit' => $doc_to_histori->p0_tgl_submit,
            'p0_pemeriksa' => $doc_to_histori->p0_pemeriksa,
            'p0_nik_gm' => $doc_to_histori->p0_nik_gm,
            'p1_nomor_p1' => $doc_to_histori->p1_nomor_p1,
            'p1_tgl_p1' => $doc_to_histori->p1_tgl_p1,
            'p1_pemeriksa' => $doc_to_histori->p1_pemeriksa,
            'p1_tgl_delivery' => $doc_to_histori->p1_tgl_delivery,
            'p1_lokasi_instal' => $doc_to_histori->p1_lokasi_instal,
            'p1_skema_bisnis' => $doc_to_histori->p1_skema_bisnis,
            'p1_skema_bayar' => $doc_to_histori->p1_skema_bayar,
            'p1_mekanisme_bayar' => $doc_to_histori->p1_mekanisme_bayar,
            'p1_tgl_kontrak_mulai' => $doc_to_histori->p1_tgl_kontrak_mulai,
            'p1_tgl_kontrak_akhir' => $doc_to_histori->p1_tgl_kontrak_akhir,
            'p1_tgl_doc_plggn' => $doc_to_histori->p1_tgl_doc_plggn,
            'p1_estimasi_harga' => $doc_to_histori->p1_estimasi_harga,
            'p1_disetujui_gm' => $doc_to_histori->p1_disetujui_gm,
            'p1_dibuat_am' => $doc_to_histori->p1_dibuat_am,
            'p1_diperiksa_manager' => $doc_to_histori->p1_diperiksa_manager,
            'file_p0' => $doc_to_histori->file_p0,
            'file_p1' => $doc_to_histori->file_p1
          ]);

          DB::connection('pgsql')->table('form_obl')->update([
            'updated_at' => Carbon::now()->translatedFormat('Y-m-d H:i:s'),
            'updated_by' => Auth::id(),
            'revisi_witel' => true,
            'revisi_witel_count' => ($doc_to_histori->revisi_witel_count + 1)
          ]);

          return redirect()->route('obl.tables')->with('status', 'Sukses Memproses Action Kembali Witel.');

        }
        catch(Throwable $e){ return redirect()->route('obl.tables')->with('status', 'Oops! Gagal Memproses Action Kembali Witel.'); }
      }
      else{ return redirect()->route('obl.tables')->with('status', 'Oops! Gagal Cek ID Dokumen OBL.'); }
    }

    public function lanjutObl(Request $request){
      // dd($request->all());
      if( $request->lo_obl_id ){
        try{
          $doc_to_histori = DB::connection('pgsql')->table('form_obl')->select('*')->where('id',$request->lo_obl_id)->first();

          DB::connection('pgsql')->table('form_obl_histori')->insert([
            'obl_id' => $doc_to_histori->id,
            'submit' => $doc_to_histori->submit,
            'revisi_witel' => $doc_to_histori->revisi_witel,
            'revisi_witel_count' => $doc_to_histori->revisi_witel_count,
            'is_draf' => $doc_to_histori->is_draf,
            'updated_at' => $doc_to_histori->updated_at,
            'updated_by' => $doc_to_histori->updated_by,
            'f1_nama_plggn' => $doc_to_histori->f1_nama_plggn,
            'f1_alamat_plggn' => $doc_to_histori->f1_alamat_plggn,
            'f1_witel' => $doc_to_histori->f1_witel,
            'f1_judul_projek' => $doc_to_histori->f1_judul_projek,
            'f1_segmen' => $doc_to_histori->f1_segmen,
            'f1_proses' => $doc_to_histori->f1_proses,
            'f1_folder' => $doc_to_histori->f1_folder,
            'f1_nilai_kb' => $doc_to_histori->f1_nilai_kb,
            'f1_no_kfs_spk' => $doc_to_histori->f1_no_kfs_spk,
            'f1_quote_kontrak' => $doc_to_histori->f1_quote_kontrak,
            'f1_nomor_akun' => $doc_to_histori->f1_nomor_akun,
            'f1_jenis_kontrak' => $doc_to_histori->f1_jenis_kontrak,
            'f1_skema_bayar' => $doc_to_histori->f1_skema_bayar,
            'f1_status_order' => $doc_to_histori->f1_status_order,
            'f1_status_sm' => $doc_to_histori->f1_status_sm,
            'f1_tgl_keterangan' => $doc_to_histori->f1_tgl_keterangan,
            'f1_keterangan' => $doc_to_histori->f1_keterangan,
            'f1_mitra_id' => $doc_to_histori->f1_mitra_id,
            'f1_pic_mitra' => $doc_to_histori->f1_pic_mitra,
            'f1_jenis_spk' => $doc_to_histori->f1_jenis_spk,
            'f1_masa_layanan_tahun' => $doc_to_histori->f1_masa_layanan_tahun,
            'f1_masa_layanan_bulan' => $doc_to_histori->f1_masa_layanan_bulan,
            'f1_masa_layanan_hari' => $doc_to_histori->f1_masa_layanan_hari,
            'f1_pic_plggn' => $doc_to_histori->f1_pic_plggn,
            'f2_nilai_kontrak' => $doc_to_histori->f2_nilai_kontrak,
            'f2_tgl_p1' => $doc_to_histori->f2_tgl_p1,
            'p2_tgl_p2' => $doc_to_histori->p2_tgl_p2,
            'p2_tgl_justifikasi' => $doc_to_histori->p2_tgl_justifikasi,
            'p2_dievaluasi_oleh' => $doc_to_histori->p2_dievaluasi_oleh,
            'p2_disetujui_oleh' => $doc_to_histori->p2_disetujui_oleh,
            'p2_pilihan_catatan' => $doc_to_histori->p2_pilihan_catatan,
            'p2_catatan' => $doc_to_histori->p2_catatan,
            'p3_tgl_p3' => $doc_to_histori->p3_tgl_p3,
            'p3_takah_p3' => $doc_to_histori->p3_takah_p3,
            'p3_pejabat_mitra_nama' => $doc_to_histori->p3_pejabat_mitra_nama,
            'p3_pejabat_mitra_alamat' => $doc_to_histori->p3_pejabat_mitra_alamat,
            'p3_pejabat_mitra_telepon' => $doc_to_histori->p3_pejabat_mitra_telepon,
            'p3_status_rapat_pengadaan' => $doc_to_histori->p3_status_rapat_pengadaan,
            'p3_tgl_rapat_pengadaan' => $doc_to_histori->p3_tgl_rapat_pengadaan,
            'p3_tmpt_rapat_pengadaan' => $doc_to_histori->p3_tmpt_rapat_pengadaan,
            'p3_tgl_terima_sp' => $doc_to_histori->p3_tgl_terima_sp,
            'p3_alamat_terima_sp' => $doc_to_histori->p3_alamat_terima_sp,
            'p3_manager_obl' => $doc_to_histori->p3_manager_obl,
            'p4_tgl_p4' => $doc_to_histori->p4_tgl_p4,
            'p4_waktu_layanan' => $doc_to_histori->p4_waktu_layanan,
            'p4_skema_bisnis' => $doc_to_histori->p4_skema_bisnis,
            'p4_mekanisme_pembayaran' => $doc_to_histori->p4_mekanisme_pembayaran,
            'p4_slg' => $doc_to_histori->p4_slg,
            'p4_fasilitator' => $doc_to_histori->p4_fasilitator,
            'p4_pengesahan' => $doc_to_histori->p4_pengesahan,
            'p5_tgl_p5' => $doc_to_histori->p5_tgl_p5,
            'p5_harga_penawaran' => $doc_to_histori->p5_harga_penawaran,
            'p5_ttd_evaluator' => $doc_to_histori->p5_ttd_evaluator,
            'p6_tgl_p6' => $doc_to_histori->p6_tgl_p6,
            'p6_ttd_bast_telkom' => $doc_to_histori->p6_ttd_bast_telkom,
            'p6_ttd_bast_mitra' => $doc_to_histori->p6_ttd_bast_mitra,
            'p6_harga_negosiasi' => $doc_to_histori->p6_harga_negosiasi,
            'p6_nama_peserta_mitra' => $doc_to_histori->p6_nama_peserta_mitra,
            'p6_jabatan_peserta_mitra' => $doc_to_histori->p6_jabatan_peserta_mitra,
            'p6_peserta_rapat_telkom' => $doc_to_histori->p6_peserta_rapat_telkom,
            'p6_pengesahan' => $doc_to_histori->p6_pengesahan,
            'p7_tgl_p7' => $doc_to_histori->p7_tgl_p7,
            'p7_takah_p7' => $doc_to_histori->p7_takah_p7,
            'p7_lampiran_berkas' => $doc_to_histori->p7_lampiran_berkas,
            'p7_harga_pekerjaan' => $doc_to_histori->p7_harga_pekerjaan,
            'p7_skema_bayar' => $doc_to_histori->p7_skema_bayar,
            'p7_pemeriksa' => $doc_to_histori->p7_pemeriksa,
            'p7_tembusan' => $doc_to_histori->p7_tembusan,
            'sp_tgl_sp' => $doc_to_histori->sp_tgl_sp,
            'sp_takah_sp' => $doc_to_histori->sp_takah_sp,
            'sp_nomor_kb' => $doc_to_histori->sp_nomor_kb,
            'p8_tgl_p8' => $doc_to_histori->p8_tgl_p8,
            'p8_takah_p8' => $doc_to_histori->p8_takah_p8,
            'wo_tgl_wo' => $doc_to_histori->wo_tgl_wo,
            'wo_takah_wo' => $doc_to_histori->wo_takah_wo,
            'wo_tgl_fo' => $doc_to_histori->wo_tgl_fo,
            'wo_nomor_kb' => $doc_to_histori->wo_nomor_kb,
            'wo_jenis_layanan' => $doc_to_histori->wo_jenis_layanan,
            'wo_jumlah_layanan' => $doc_to_histori->wo_jumlah_layanan,
            'wo_harga_ke_plggn' => $doc_to_histori->wo_harga_ke_plggn,
            'wo_onetime_charge_plggn' => $doc_to_histori->wo_onetime_charge_plggn,
            'wo_monthly_plggn' => $doc_to_histori->wo_monthly_plggn,
            'wo_onetime_charge_telkom' => $doc_to_histori->wo_onetime_charge_telkom,
            'wo_persen_telkom' => $doc_to_histori->wo_persen_telkom,
            'wo_monthly_telkom' => $doc_to_histori->wo_monthly_telkom,
            'wo_onetime_charge_mitra' => $doc_to_histori->wo_onetime_charge_mitra,
            'wo_persen_mitra' => $doc_to_histori->wo_persen_mitra,
            'wo_monthly_mitra' => $doc_to_histori->wo_monthly_mitra,
            'kl_tgl_kl' => $doc_to_histori->kl_tgl_kl,
            'kl_takah_kl' => $doc_to_histori->kl_takah_kl,
            'kl_nomor_kb' => $doc_to_histori->kl_nomor_kb,
            'kl_no_kl_mitra' => $doc_to_histori->kl_no_kl_mitra,
            'kl_tempat_ttd_kl' => $doc_to_histori->kl_tempat_ttd_kl,
            'kl_notaris' => $doc_to_histori->kl_notaris,
            'kl_akta_notaris' => $doc_to_histori->kl_akta_notaris,
            'kl_tgl_akta_notaris' => $doc_to_histori->kl_tgl_akta_notaris,
            'kl_nama_pejabat_telkom' => $doc_to_histori->kl_nama_pejabat_telkom,
            'kl_jabatan_pejabat_telkom' => $doc_to_histori->kl_jabatan_pejabat_telkom,
            'kl_npwp_mitra' => $doc_to_histori->kl_npwp_mitra,
            'kl_no_anggaran_mitra' => $doc_to_histori->kl_no_anggaran_mitra,
            'kl_tgl_anggaran_mitra' => $doc_to_histori->kl_tgl_anggaran_mitra,
            'kl_nama_pejabat_mitra' => $doc_to_histori->kl_nama_pejabat_mitra,
            'kl_jabatan_pejabat_mitra' => $doc_to_histori->kl_jabatan_pejabat_mitra,
            'kl_no_skm' => $doc_to_histori->kl_no_skm,
            'kl_tgl_skm' => $doc_to_histori->kl_tgl_skm,
            'kl_perihal_skm' => $doc_to_histori->kl_perihal_skm,
            'kl_tgl_akhir_kl' => $doc_to_histori->kl_tgl_akhir_kl,
            'kl_bayar_dp' => $doc_to_histori->kl_bayar_dp,
            'kl_nama_bank_mitra' => $doc_to_histori->kl_nama_bank_mitra,
            'kl_cabang_bank_mitra' => $doc_to_histori->kl_cabang_bank_mitra,
            'kl_rek_bank_mitra' => $doc_to_histori->kl_rek_bank_mitra,
            'kl_an_bank_mitra' => $doc_to_histori->kl_an_bank_mitra,
            'file_p2' => $doc_to_histori->file_p2,
            'file_p3' => $doc_to_histori->file_p3,
            'file_p4' => $doc_to_histori->file_p4,
            'file_p5' => $doc_to_histori->file_p5,
            'file_p6' => $doc_to_histori->file_p6,
            'file_p7' => $doc_to_histori->file_p7,
            'file_p8' => $doc_to_histori->file_p8,
            'file_sp' => $doc_to_histori->file_sp,
            'file_wo' => $doc_to_histori->file_wo,
            'file_kl' => $doc_to_histori->file_kl,
            'p0_nomor_p0' => $doc_to_histori->p0_nomor_p0,
            'p0_nik_am' => $doc_to_histori->p0_nik_am,
            'p0_nik_manager' => $doc_to_histori->p0_nik_manager,
            'p0_tgl_submit' => $doc_to_histori->p0_tgl_submit,
            'p0_pemeriksa' => $doc_to_histori->p0_pemeriksa,
            'p0_nik_gm' => $doc_to_histori->p0_nik_gm,
            'p1_nomor_p1' => $doc_to_histori->p1_nomor_p1,
            'p1_tgl_p1' => $doc_to_histori->p1_tgl_p1,
            'p1_pemeriksa' => $doc_to_histori->p1_pemeriksa,
            'p1_tgl_delivery' => $doc_to_histori->p1_tgl_delivery,
            'p1_lokasi_instal' => $doc_to_histori->p1_lokasi_instal,
            'p1_skema_bisnis' => $doc_to_histori->p1_skema_bisnis,
            'p1_skema_bayar' => $doc_to_histori->p1_skema_bayar,
            'p1_mekanisme_bayar' => $doc_to_histori->p1_mekanisme_bayar,
            'p1_tgl_kontrak_mulai' => $doc_to_histori->p1_tgl_kontrak_mulai,
            'p1_tgl_kontrak_akhir' => $doc_to_histori->p1_tgl_kontrak_akhir,
            'p1_tgl_doc_plggn' => $doc_to_histori->p1_tgl_doc_plggn,
            'p1_estimasi_harga' => $doc_to_histori->p1_estimasi_harga,
            'p1_disetujui_gm' => $doc_to_histori->p1_disetujui_gm,
            'p1_dibuat_am' => $doc_to_histori->p1_dibuat_am,
            'p1_diperiksa_manager' => $doc_to_histori->p1_diperiksa_manager,
            'file_p0' => $doc_to_histori->file_p0,
            'file_p1' => $doc_to_histori->file_p1
          ]);

          DB::connection('pgsql')->table('form_obl')->where('id',$request->lo_obl_id)->update([
            'updated_at' => Carbon::now()->translatedFormat('Y-m-d H:i:s'),
            'updated_by' => Auth::id(),
            'f1_proses' => 'obl'
          ]);

          return redirect()->route('obl.tables')->with('status', 'Sukses Memproses Action Lanjut OBL.');

        }
        catch(Throwable $e){ return redirect()->route('obl.tables')->with('status', 'Oops! Gagal Memproses Action Lanjut OBL.'); }
      }
      else{ return redirect()->route('obl.tables')->with('status', 'Oops! Gagal Cek ID Dokuemn OBL.'); }
    }
}
